In [1]:
pip install faiss-cpu

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 10.6 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 13.6 MB/s eta 0:00:0000:0100:01

[notice] A new release of pip is available: 23.0.1 -> 25.2
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install numpy requests

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.8/64.8 kB 2.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 161.2/161.2 kB 8.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.7/207.7 kB 10.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.8/129.8 kB 9.3 MB/s eta 0:00:00

[notice] A new release of pip is available: 23.0.1 -> 25.2
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [1]:
pip install faiss-cpu

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 13.8 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 13.8 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [faiss-cpu]/2 [faiss-cpu]
Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install numpy requests

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5/5 [requests]4/5 [requests]
Note: you may need to restart the kernel to use updated packages.


In [3]:
data = """
Making an Impact
Helping Millions of Students Succeed
Sudhanshu's commitment to affordable education wasn't just a business strategy—it was his life's mission. Over the years, iNeuron has helped over 1.5 million students from 34+ countries, providing them with the skills they need to succeed in today's competitive job market. Many of these students, like Sudhanshu himself, came from disadvantaged backgrounds. They saw iNeuron as a lifeline—an opportunity to rise above their circumstances.

In 2022, iNeuron was acquired by PhysicsWallah in a deal worth ₹250 crore. While this acquisition was a significant milestone, Sudhanshu remained focused on his mission. Even after the acquisition, iNeuron continued to offer some of the most affordable and accessible tech courses in the world."""

In [4]:
clean_data = data.strip()

In [5]:
print(clean_data)

Making an Impact
Helping Millions of Students Succeed
Sudhanshu's commitment to affordable education wasn't just a business strategy—it was his life's mission. Over the years, iNeuron has helped over 1.5 million students from 34+ countries, providing them with the skills they need to succeed in today's competitive job market. Many of these students, like Sudhanshu himself, came from disadvantaged backgrounds. They saw iNeuron as a lifeline—an opportunity to rise above their circumstances.

In 2022, iNeuron was acquired by PhysicsWallah in a deal worth ₹250 crore. While this acquisition was a significant milestone, Sudhanshu remained focused on his mission. Even after the acquisition, iNeuron continued to offer some of the most affordable and accessible tech courses in the world.


In [13]:
max_char = 300
overlap = 100
chunks = []
i = 0
while i < len(clean_data):
    piece = clean_data[i:i+max_char]
    chunks.append(piece)
    i = i + max_char - overlap

In [15]:
len(chunks)

4

In [16]:
import requests
import numpy as np

def generate_embeddings(text):
    url = "https://api.euron.one/api/v1/euri/embeddings"
    headers = {
        "Content-Type": "application/json",
        "Authorization": "Bearer euri-76db4feb51b874646f3bd3cc68d8675a9ff86ca815cf720a22564b08801ae17c"
    }
    payload = {
        "input": text,
        "model": "text-embedding-3-small"
    }

    response = requests.post(url, headers=headers, json=payload)
    data = response.json()
    
    embedding = np.array(data['data'][0]['embedding'])
    
    return embedding

text = "The weather is sunny today."

embedding = generate_embeddings(text)

In [17]:
for i in chunks:
    embedding = generate_embeddings(i)
    print(embedding)

[ 0.01636502 -0.01330146  0.04360536 ... -0.00716132 -0.00025957
  0.00777273]
[-0.02781129  0.00346     0.04792786 ... -0.01521874 -0.01743786
 -0.00741897]
[-0.02118863 -0.03512738  0.01884393 ... -0.01878639  0.009573
  0.02058447]
[-0.01897111 -0.02526139  0.02755397 ... -0.01662122 -0.00260423
  0.02576289]


In [21]:
for idx, chunk in enumerate(chunks):
    embeddings = generate_embeddings(chunk)
    print(f"chunk {idx+1} embeddings {embeddings}")

chunk 1 embeddings [ 0.01636502 -0.01330146  0.04360536 ... -0.00716132 -0.00025957
  0.00777273]
chunk 2 embeddings [-0.02781193  0.00343053  0.04798149 ... -0.01521909 -0.01743826
 -0.00741914]
chunk 3 embeddings [-0.02118863 -0.03512738  0.01884393 ... -0.01878639  0.009573
  0.02058447]
chunk 4 embeddings [-0.01897111 -0.02526139  0.02755397 ... -0.01662122 -0.00260423
  0.02576289]


In [22]:
emb_list = []
meta= []
for idx,chunk in enumerate(chunks):
    vec = generate_embeddings(chunk)
    emb_list.append(vec.astype("float32"))
    
    meta.append({"id": idx, "text": chunk})

In [23]:
meta

[{'id': 0,
  'text': "Making an Impact\nHelping Millions of Students Succeed\nSudhanshu's commitment to affordable education wasn't just a business strategy—it was his life's mission. Over the years, iNeuron has helped over 1.5 million students from 34+ countries, providing them with the skills they need to succeed in toda"},
 {'id': 1,
  'text': "1.5 million students from 34+ countries, providing them with the skills they need to succeed in today's competitive job market. Many of these students, like Sudhanshu himself, came from disadvantaged backgrounds. They saw iNeuron as a lifeline—an opportunity to rise above their circumstances.\n\nIn 20"},
 {'id': 2,
  'text': 'backgrounds. They saw iNeuron as a lifeline—an opportunity to rise above their circumstances.\n\nIn 2022, iNeuron was acquired by PhysicsWallah in a deal worth ₹250 crore. While this acquisition was a significant milestone, Sudhanshu remained focused on his mission. Even after the acquisition, iNeuron'},
 {'id': 3,
  'te

In [24]:
emb_list

[array([ 0.01646678, -0.01327756,  0.04386802, ..., -0.00723757,
        -0.00036021,  0.00765412], shape=(1536,), dtype=float32),
 array([-0.02783641,  0.00345329,  0.04789964, ..., -0.01521811,
        -0.01743715, -0.00740554], shape=(1536,), dtype=float32),
 array([-0.02119237, -0.03513358,  0.01877532, ..., -0.01876093,
         0.00953153,  0.02064566], shape=(1536,), dtype=float32),
 array([-0.01897111, -0.02526139,  0.02755397, ..., -0.01662122,
        -0.00260423,  0.02576289], shape=(1536,), dtype=float32)]

In [25]:
xb = np.vstack(emb_list)

In [26]:
xb

array([[ 0.01646678, -0.01327756,  0.04386802, ..., -0.00723757,
        -0.00036021,  0.00765412],
       [-0.02783641,  0.00345329,  0.04789964, ..., -0.01521811,
        -0.01743715, -0.00740554],
       [-0.02119237, -0.03513358,  0.01877532, ..., -0.01876093,
         0.00953153,  0.02064566],
       [-0.01897111, -0.02526139,  0.02755397, ..., -0.01662122,
        -0.00260423,  0.02576289]], shape=(4, 1536), dtype=float32)

In [27]:
import faiss

In [28]:
faiss.normalize_L2(xb)

In [29]:
index = faiss.IndexFlatIP(1536)
index.add(xb)